version: "3.9"

services:
  devel:
    build: .
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_REGION=ap-northeast-1
    volumes:
      - .:/work
      - cargo-store:/root/.cargo
      - target-store:/work/target
  localstack:
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RUST_BACKTRACE=1
    image: localstack/localstack
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    volumes:
      - localstack-store:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-db-store:/data/db
      - mongo-config-store:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  cargo-store:
  localstack-store:
  mongo-config-store:
  mongo-db-store:
  target-store:
