version: "3.9"

services:
  devel:
    build: .
    volumes:
      - .:/work
      - cargo-store:$HOME/.cargo
      - target-store:/work/target
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-db-store:/data/db
      - mongo-config-store:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  cargo-store:
  mongo-config-store:
  mongo-db-store:
  target-store:
